{
  imports = [
    ./common.nix
    ./fonts.nix
    ./gstreamer.nix
    ./hibernate.nix
    ./ima.nix
    ./japanese.nix
    ./kpro.nix
    ./machines/default.nix
    ./niri.nix
    ./nixos-artwork.nix
    ./packages.nix
    ./personal.nix
    ./power-targets.nix
    ./secureboot.nix
    ./selinux.nix
    ./tpm2.nix
    ./windows-vm.nix
  ];
}
