# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  nixpkgs.system = "x86_64-linux";

  boot = {
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    resumeDevice = "/dev/disk/by-uuid/087b3e39-7001-4677-b290-8dd45c64bb37";
    initrd = {
      systemd.enable = true;
      kernelModules = [ ];
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/c73fb028-c49b-4d3e-8628-39e326535d46";
      fsType = "btrfs";
      options = [
        "autodefrag"
        "commit=120"
        "compress=zstd"
        "noatime"
        "space_cache=v2"
        "subvol=@"
      ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/c73fb028-c49b-4d3e-8628-39e326535d46";
      fsType = "btrfs";
      options = [
        "autodefrag"
        "commit=120"
        "compress=zstd"
        "noatime"
        "space_cache=v2"
        "subvol=@home"
      ];
    };

    "/efi" = {
      device = "/dev/disk/by-uuid/DA91-D0F6";
      fsType = "vfat";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/8057-31F0";
      fsType = "vfat";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/087b3e39-7001-4677-b290-8dd45c64bb37"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.sensor.iio.enable = true;
}
