keys:
  - &action age1829ry46h0ctesxrehhuehw4sxwa5rcpwamjldne3jjzj9gjthq9qflh2vh
  - &micky age14f25vp3y5z3k8qc7u52srq67jhxzftclgw3c9xsu0avczprh3ykqkjc5ln
creation_rules:
  - path_regex: secrets/secrets.yml$
    key_groups:
      - age:
          - *action
          - *micky
