# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices.cryptroot.device = "/dev/disk/by-uuid/4ec820c4-37c3-4925-9439-8bcec0c3ef62";
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    resumeDevice = "/dev/disk/by-uuid/87cb250e-f9a3-40b2-877c-fd07e77535ea";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/77b7cb82-87a1-45ec-8306-1a8edad64fd1";
    fsType = "btrfs";
    options = [
      "defaults"

      "autodefrag"
      "commit=120"
      "compress=zstd"
      "noatime"
      "nosuid"
      "space_cache=v2"
      "subvol=@"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/41EB-3189";
    fsType = "vfat";
    options = [
      "defaults"

      "dmask=0077"
      "fmask=0177"
      "nodev"
      "noexec"
      "nosuid"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/87cb250e-f9a3-40b2-877c-fd07e77535ea"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
