name: CI

# update note:
# The hash of the actions used can be updated with actions-up
# $ nix shell .#bun -c bunx actions-up

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - "aarch64-darwin"
          - "aarch64-linux"
          - "x86_64-linux"
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm')
      || (matrix.system == 'aarch64-darwin' && 'macos-latest') }}

    permissions:
      contents: read
      id-token: write # required for OIDC

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: enable unprivileged userns clone
        if: runner.os == 'Linux'
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo sysctl -w kernel.unprivileged_userns_clone=1
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        if: runner.os == 'Linux'
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          extra_nix_config: |
            fallback = true
            accept-flake-config = true
            system = ${{ matrix.system }}
            extra-substituters = https://niks3-storage.gweb.ihavenojob.work?priority=99
            extra-trusted-public-keys = niks3-cache:RW+9UW/AgeDvEawJndPbzNVYQcDPjXA4J23srAi5+sE=

      - name: Run checks
        run: nix build --log-format bar-with-logs ".#ci"

      - name: Get OIDC token
        id: oidc
        run: |
          token=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ vars.NIKS3_SERVER_URL }}" | jq -r '.value')
          echo "::add-mask::$token"
          echo "token=$token" >> "$GITHUB_OUTPUT"

      - name: Upload Cache
        if: always()
        continue-on-error: true
        run: |
          nix profile add --inputs-from . "nixpkgs#niks3"
          nix path-info --all | \
            grep -v "*.drv" | \
            xargs -n 50 niks3 push --server-url "${{ vars.NIKS3_SERVER_URL }}" --auth-token "${{ steps.oidc.outputs.token }}"
          
